/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/jimny.glb -o components/JimnyModel.tsx 
Author: luyssport (https://sketchfab.com/luyssport)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/che-1e529f4b8efc4f20925957a9a4208dcd
Title: cHe
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane004_0: THREE.Mesh
    Cube005_0: THREE.Mesh
    GP_Layer_CUGP_Layer_0: THREE.Mesh
    Plane_0: THREE.Mesh
    Cube000_0: THREE.Mesh
    Cube001_0: THREE.Mesh
    Cube002_0: THREE.Mesh
    Cube004_0: THREE.Mesh
  }
  materials: {
    shadow: THREE.MeshBasicMaterial
    ruedas: THREE.MeshBasicMaterial
    clouds: THREE.MeshBasicMaterial
    cristales: THREE.MeshBasicMaterial
    carroceria: THREE.MeshBasicMaterial
    interior: THREE.MeshBasicMaterial
    chasis: THREE.MeshBasicMaterial
  }
}

// Changed the props type here from JSX.IntrinsicElements['group'] to GroupProps
export function Model(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/jimny.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Plane004_0.geometry} material={materials.shadow} position={[1.68, 2.771, -1.28]} rotation={[-0.057, 0, 0]} scale={7.469} />
        <mesh geometry={nodes.Cube005_0.geometry} material={materials.ruedas} position={[0.005, 0.407, 0.054]} rotation={[-0.057, -0.017, 0]} />
        <mesh geometry={nodes.GP_Layer_CUGP_Layer_0.geometry} material={materials.clouds} position={[0, 0, -4.913]} rotation={[Math.PI / 2, -1.553, 0]} />
        <mesh geometry={nodes.Plane_0.geometry} material={materials.shadow} />
        <mesh geometry={nodes.Cube000_0.geometry} material={materials.cristales} position={[0.005, 0.407, 0.054]} rotation={[-0.057, -0.017, 0]} />
        <mesh geometry={nodes.Cube001_0.geometry} material={materials.carroceria} position={[0.005, 0.407, 0.054]} rotation={[-0.057, -0.017, 0]} />
        <mesh geometry={nodes.Cube002_0.geometry} material={materials.interior} position={[0.005, 0.407, 0.054]} rotation={[-0.057, -0.017, 0]} />
        <mesh geometry={nodes.Cube004_0.geometry} material={materials.chasis} position={[0.005, 0.407, 0.054]} rotation={[-0.057, -0.017, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/jimny.glb')